# Generated by Django 5.1.1 on 2024-11-12 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wrap',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='topartist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topsong',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wrap',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='topartist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topartist',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topsong',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topsong',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wrap',
            name='minutes_listened',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wrap',
            name='top_genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wrap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
