# Generated by Django 5.1.3 on 2024-11-26 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duowrap',
            name='year',
        ),
        migrations.AddField(
            model_name='duowrap',
            name='wrap_name',
            field=models.CharField(default='duo wrap', max_length=200),
        ),
        migrations.AddField(
            model_name='wrap',
            name='day',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
