# Generated by Django 5.1.3 on 2024-11-30 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wrap",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="wrap",
            name="term_type",
            field=models.CharField(
                choices=[
                    ("short", "Short-Term"),
                    ("medium", "Medium-Term"),
                    ("long", "Long-Term"),
                ],
                default="short",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wrap",
            unique_together={("user", "name", "term_type")},
        ),
    ]
