# Generated by Django 5.1.3 on 2024-11-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrap',
            name='day',
        ),
        migrations.AddField(
            model_name='wrap',
            name='name',
            field=models.CharField(default='wrap default name', max_length=100),
            preserve_default=False,
        ),
    ]
