# Generated by Django 5.1.3 on 2024-11-30 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_wrap_unique_together_wrap_term_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wrap",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_wraps", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="wrap",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
