# Generated by Django 5.1.3 on 2024-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_wrap_day_wrap_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wrap',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='wrap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wrap',
            name='song_recommendationsJSON',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='wrap',
            name='top_artistsJSON',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='wrap',
            name='top_songsJSON',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RemoveField(
            model_name='wrap',
            name='minutes_listened',
        ),
        migrations.RemoveField(
            model_name='wrap',
            name='year',
        ),
    ]
