# Generated by Django 5.1.3 on 2024-11-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_duowrap_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='duowrap_request',
            name='wrap_name',
            field=models.CharField(default='Wrap1', max_length=100),
            preserve_default=False,
        ),
    ]
