# Generated by Django 5.1.3 on 2024-11-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_wrap_options_alter_wrap_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrap',
            name='song_recommendationsJSON',
        ),
        migrations.AddField(
            model_name='wrap',
            name='minutes_listened',
            field=models.IntegerField(default=0),
        ),
    ]
